//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFitnessEntities : DbContext
    {
        public MyFitnessEntities()
            : base("name=MyFitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avoirRole> avoirRoles { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<coach> coaches { get; set; }
        public virtual DbSet<composer> composers { get; set; }
        public virtual DbSet<exercice> exercices { get; set; }
        public virtual DbSet<gestionnaire> gestionnaires { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<malady> maladies { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<repa> repas { get; set; }
        public virtual DbSet<repons> reponses { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<specNutrition> specNutritions { get; set; }
        public virtual DbSet<typeIngredient> typeIngredients { get; set; }
        public virtual DbSet<typeOfExercice> typeOfExercices { get; set; }
        public virtual DbSet<typeRepa> typeRepas { get; set; }
    }
}
