//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class repa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repa()
        {
            this.composers = new HashSet<composer>();
            this.maladies = new HashSet<malady>();
            this.reponses = new HashSet<repons>();
        }
    
        public string label { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public int idSpecN { get; set; }
        public string label_typeRepas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<composer> composers { get; set; }
        public virtual specNutrition specNutrition { get; set; }
        public virtual typeRepa typeRepa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<malady> maladies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repons> reponses { get; set; }
    }
}
